---
- name: 1. install httpd
  yum: name=httpd state=present

- name: 2. install PHP module for Apache
  yum: name={{item}} state=present
  with_items: 
  - php
  - php-mysql
  - php-pdo
  - php-gd
  - php-mbstring
  - php-soap
  - php-fpm
  - php-pear

- name: 3. start httpd
  service: name=httpd state=running enabled=yes

- name: 4. install Hello World PHP script
  copy: src=index.html dest=/var/www/html/index.html 

- name: 5. Add rules firewall
  action: command /usr/bin/firewall-cmd --permanent --add-port=80/tcp

- name: 6. redemarrage de parfeu
  service:  name=firewalld state=restarted

- name: restart httpd
  service: name=httpd state=restarted
